<?php
/**
 * Function to disable SEO Tags generated by Rank Math
 */

add_filter( 'rank_math/frontend/robots', function( $robots ) {

	// Current request URI
	$request_uri = $_SERVER['REQUEST_URI'];

	// Match /download/0/ OR /download/any-number/
	if ( strpos( $request_uri, '/download/' ) !== false ) {
		$robots['index']  = 'noindex';
		$robots['follow'] = 'nofollow';
	}

	return $robots;
});