<?php
/**
 * Function to disable SEO Tags generated by Rank Math
 */

add_filter( 'rank_math/frontend/robots', function( $robots ) {

	// Current request URI
	$request_uri = $_SERVER['REQUEST_URI'];

	// Match /download/0/ OR /download/any-number/
	if ( strpos( $request_uri, '/download/' ) !== false ) {
		$robots['index']  = 'noindex';
		$robots['follow'] = 'follow';
	}

	return $robots;
});

// Support Yoast SEO robots tag
add_filter( 'wpseo_robots', function( $robots ) {
	if ( strpos( $_SERVER['REQUEST_URI'], '/download/' ) !== false ) {
		return 'noindex, follow';
	}
	return $robots;
});

// Support WordPress Core robots tag
add_filter( 'wp_robots', function( $robots ) {
	if ( strpos( $_SERVER['REQUEST_URI'], '/download/' ) !== false ) {
		$robots['noindex'] = true;
		$robots['follow']  = true;
		unset($robots['nofollow']);
	}
	return $robots;
});